In [1]:
!pip install datasets jiwer openai-whisper speechbrain torchaudio librosa pandas

Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Collecting jiwer
  Downloading jiwer-4.0.0-py3-none-any.whl.metadata (3.3 kB)
Collecting openai-whisper
  Downloading openai_whisper-20250625.tar.gz (803 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 803.2/803.2 kB 20.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting speechbrain
  Downloading speechbrain-1.1.0-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: torchaudio in /usr/local/lib/python3.12/dist-packages (2.11.0+cu128)
Requirement already satisfied: librosa in /usr/local/lib/python3.12/dist-packages (0.11.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.29.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.7.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (1.17.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: click>=8.1.8 in /usr/local/lib/python3.12/dist-packages (from jiwer) (8.4.1)
Collecting rapidfuzz>=3.9.7 (from jiwer)
  Downloading rapidfuzz-3.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Requirement already satisfied: more-itertools in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (10.8.0)
Requirement already satisfied: numba in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (0.60.0)
Requirement already satisfied: tiktoken in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (0.13.0)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (2.11.0+cu128)
Requirement already satisfied: triton>=2 in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (3.6.0)
Collecting hyperpyyaml>=0.0.1 (from speechbrain)
  Downloading hyperpyyaml-1.2.3-py3-none-any.whl.metadata (8.1 kB)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.12/dist-packages (from speechbrain) (1.5.3)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from speechbrain) (1.16.3)
Requirement already satisfied: sentencepiece>=0.1.91 in /usr/local/lib/python3.12/dist-packages (from speechbrain) (0.2.1)
Requirement already satisfied: soundfile>=0.12.1 in /usr/local/lib/python3.12/dist-packages (from speechbrain) (0.13.1)
Requirement already satisfied: audioread>=2.1.9 in /usr/local/lib/python3.12/dist-packages (from librosa) (3.1.0)
Requirement already satisfied: scikit-learn>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from librosa) (1.6.1)
Requirement already satisfied: decorator>=4.3.0 in /usr/local/lib/python3.12/dist-packages (from librosa) (4.4.2)
Requirement already satisfied: pooch>=1.1 in /usr/local/lib/python3.12/dist-packages (from librosa) (1.9.0)
Requirement already satisfied: soxr>=0.3.2 in /usr/local/lib/python3.12/dist-packages (from librosa) (1.1.0)
Requirement already satisfied: typing_extensions>=4.1.1 in /usr/local/lib/python3.12/dist-packages (from librosa) (4.15.0)
Requirement already satisfied: lazy_loader>=0.1 in /usr/local/lib/python3.12/dist-packages (from librosa) (0.5)
Requirement already satisfied: msgpack>=1.0 in /usr/local/lib/python3.12/dist-packages (from librosa) (1.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.14.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (1.5.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (0.28.1)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (0.25.1)
Collecting ruamel.yaml<0.19.0,>=0.17.28 (from hyperpyyaml>=0.0.1->speechbrain)
  Downloading ruamel_yaml-0.18.17-py3-none-any.whl.metadata (27 kB)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba->openai-whisper) (0.43.0)
Requirement already satisfied: platformdirs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from pooch>=1.1->librosa) (4.10.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.5.20)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.1.0->librosa) (3.6.0)
Requirement already satisfied: cffi>=1.0 in /usr/local/lib/python3.12/dist-packages (from soundfile>=0.12.1->speechbrain) (2.0.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (3.1.6)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->openai-whisper) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (3.4.5)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->openai-whisper) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->openai-whisper) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->openai-whisper) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->openai-whisper) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->openai-whisper) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->openai-whisper) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->openai-whisper) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->openai-whisper) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->openai-whisper) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->openai-whisper) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->openai-whisper) (12.8.90)
Requirement already satisfied: regex in /usr/local/lib/python3.12/dist-packages (from tiktoken->openai-whisper) (2025.11.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.24.2)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.0->soundfile>=0.12.1->speechbrain) (3.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch->openai-whisper) (1.5.5)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (0.16.0)
Collecting ruamel.yaml.clib>=0.2.15 (from ruamel.yaml<0.19.0,>=0.17.28->hyperpyyaml>=0.0.1->speechbrain)
  Downloading ruamel_yaml_clib-0.2.15-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (3.5 kB)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch->openai-whisper) (1.3.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.24.0->datasets) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.24.0->datasets) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.24.0->datasets) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch->openai-whisper) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.24.0->datasets) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.24.0->datasets) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.24.0->datasets) (0.1.2)
Downloading jiwer-4.0.0-py3-none-any.whl (23 kB)
Downloading speechbrain-1.1.0-py3-none-any.whl (2.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 38.1 MB/s eta 0:00:00
Downloading hyperpyyaml-1.2.3-py3-none-any.whl (16 kB)
Downloading rapidfuzz-3.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 51.6 MB/s eta 0:00:00
Downloading ruamel_yaml-0.18.17-py3-none-any.whl (121 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 kB 8.5 MB/s eta 0:00:00
Downloading ruamel_yaml_clib-0.2.15-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (788 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 788.2/788.2 kB 35.3 MB/s eta 0:00:00
Building wheels for collected packages: openai-whisper
  Building wheel for openai-whisper (pyproject.toml) ... done
  Created wheel for openai-whisper: filename=openai_whisper-20250625-py3-none-any.whl size=803979 sha256=bfee073aa9b31d790e5722890865accd2d06b5e48fc9267befa300a0cd219cbb
  Stored in directory: /root/.cache/pip/wheels/61/d2/20/09ec9bef734d126cba375b15898010b6cc28578d8afdde5869
Successfully built openai-whisper
Installing collected packages: ruamel.yaml.clib, rapidfuzz, ruamel.yaml, jiwer, hyperpyyaml, speechbrain, openai-whisper
Successfully installed hyperpyyaml-1.2.3 jiwer-4.0.0 openai-whisper-20250625 rapidfuzz-3.14.5 ruamel.yaml-0.18.17 ruamel.yaml.clib-0.2.15 speechbrain-1.1.0

In [2]:
!pip install --upgrade sympy

Requirement already satisfied: sympy in /usr/local/lib/python3.12/dist-packages (1.14.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy) (1.3.0)

In [2]:
import os
import re
import torch
import librosa
import numpy as np
import pandas as pd
import whisper
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModel, AutoConfig
from huggingface_hub import login
from speechbrain.inference.speaker import EncoderClassifier
from jiwer import wer

# ==========================================
# 1. CONFIGURATION & AUTHENTICATION
# ==========================================
my_token = "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"
print("Logging into Hugging Face...")
login(token=my_token)

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}\n")

# Number of samples to evaluate for this test run
NUM_SAMPLES_TO_TEST = 20

# ==========================================
# 2. LOAD TTS MODEL (VITS Rasa 13)
# ==========================================
print("Loading VITS Rasa 13...")
vits_id = "ai4bharat/vits_rasa_13"
vits_tokenizer = AutoTokenizer.from_pretrained(vits_id, trust_remote_code=True)

# Patch configuration to meet strict transformers requirements
vits_config = AutoConfig.from_pretrained(vits_id, trust_remote_code=True)
vits_config.pad_token_id = 0
vits_model = AutoModel.from_pretrained(vits_id, config=vits_config, trust_remote_code=True).to(device)

# ==========================================
# 3. LOAD EVALUATION MODELS
# ==========================================
print("Loading Whisper ASR (Medium)...")
asr_model = whisper.load_model("medium")

print("Loading SpeechBrain S-SIM Model...")
try:
    spk_model = EncoderClassifier.from_hparams(source="speechbrain/spkrec-ecapa-voxceleb", savedir="tmp_dir")
    has_spk_model = True
except Exception as e:
    print(f"Warning: Could not load SpeechBrain. Error: {e}")
    has_spk_model = False

# ==========================================
# 4. HELPER FUNCTIONS
# ==========================================
def calculate_snr(y):
    signal_power = np.mean(y**2)
    noise_floor = np.mean(y[np.abs(y) < np.percentile(np.abs(y), 10)]**2) + 1e-10
    return 10 * np.log10(signal_power / noise_floor)

def clean_hindi_text(text):
    return re.sub(r'[^\u0900-\u097F\s]', '', text).strip()

# ==========================================
# 5. LOAD DATASET & EVALUATE
# ==========================================
print("Loading IndicVoices-R (Hindi Subset)...")
# 🚨 FIXED: Changed "Hi" to "Hindi"
ds = load_dataset("ai4bharat/indicvoices_r", "Hindi", split="train", streaming=True)

results_list = []
print(f"\nStarting Evaluation for {NUM_SAMPLES_TO_TEST} samples...")

for idx, sample in enumerate(ds):
    if idx >= NUM_SAMPLES_TO_TEST:
        break

    print(f"Processing sample {idx + 1}/{NUM_SAMPLES_TO_TEST}...")

    # Extract data from the dataset sample
    target_text = sample['text']
    ref_audio_array = sample['audio']['array']
    ref_sr = sample['audio']['sampling_rate']

    # Resample reference audio to 16kHz for SpeechBrain if needed
    if ref_sr != 16000:
        ref_audio_array = librosa.resample(y=ref_audio_array, orig_sr=ref_sr, target_sr=16000)

    metrics = {
        "Sample Index": idx,
        "Original Text": target_text
    }

    try:
        # Generate new audio using VITS
        inputs_v = vits_tokenizer(target_text, return_tensors="pt").to(device)
        with torch.no_grad():
            output = vits_model(
                inputs_v['input_ids'],
                speaker_id=1,  # Defaulting to Female speaker for test
                emotion_id=0
            )

        gen_audio = output.waveform.cpu().numpy().squeeze()

        # Save temporarily for Whisper to read
        temp_wav = "temp_eval.wav"
        import soundfile as sf
        sf.write(temp_wav, gen_audio, vits_model.config.sampling_rate)

        # --- Metric 1: Intelligibility (WER) ---
        # 🚨 FIXED: Changed language to "hi" for Whisper
        transcription_result = asr_model.transcribe(temp_wav, language="hi", task="transcribe", fp16=False)
        transcription = transcription_result["text"]

        clean_target = clean_hindi_text(target_text)
        clean_trans = clean_hindi_text(transcription)

        if len(clean_target) > 0 and len(clean_trans) > 0:
            metrics["WER"] = round(wer(clean_target, clean_trans), 3)
        else:
            metrics["WER"] = 1.0

        metrics["Transcribed Text"] = transcription.strip()

        # --- Metric 2: Clarity (SNR) ---
        metrics["SNR (dB)"] = round(calculate_snr(gen_audio), 2)

        # --- Metric 3: Speaker Similarity ---
        if has_spk_model:
            emb_gen = spk_model.encode_batch(torch.tensor(gen_audio).unsqueeze(0))
            emb_ref = spk_model.encode_batch(torch.tensor(ref_audio_array).unsqueeze(0).float())
            cos = torch.nn.CosineSimilarity(dim=-1)
            metrics["S-SIM"] = round(cos(emb_gen, emb_ref).item(), 3)

    except Exception as e:
        print(f"Error on sample {idx}: {e}")
        metrics["WER"] = "Error"
        metrics["SNR (dB)"] = "Error"
        metrics["S-SIM"] = "Error"
        metrics["Transcribed Text"] = "Error"

    results_list.append(metrics)

# Clean up temp file
if os.path.exists("temp_eval.wav"):
    os.remove("temp_eval.wav")

# ==========================================
# 6. EXPORT RESULTS
# ==========================================
df_dataset_eval = pd.DataFrame(results_list)
output_csv = "IndicVoices_VITS_Evaluation.csv"
df_dataset_eval.to_csv(output_csv, index=False)

print(f"\n✅ Dataset Evaluation Complete! Results saved to {output_csv}")
print(f"Average WER: {pd.to_numeric(df_dataset_eval['WER'], errors='coerce').mean():.3f}")
print(f"Average SNR: {pd.to_numeric(df_dataset_eval['SNR (dB)'], errors='coerce').mean():.2f} dB")
print(f"Average S-SIM: {pd.to_numeric(df_dataset_eval['S-SIM'], errors='coerce').mean():.3f}")

import IPython
display(df_dataset_eval.head())

KeyboardInterrupt:

In [3]:
import os
import re
import torch
import librosa
import numpy as np
import pandas as pd
import whisper
import soundfile as sf
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModel, AutoConfig
from huggingface_hub import login
from speechbrain.inference.speaker import EncoderClassifier
from jiwer import wer

# ==========================================
# 1. CONFIGURATION & AUTHENTICATION
# ==========================================
my_token = "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"
print("Logging into Hugging Face...")
login(token=my_token)

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}\n")

NUM_SAMPLES_TO_TEST = 20

# 🚨 NEW: Create a directory to save the audio files permanently
output_dir = "IndicVoices_Audio"
os.makedirs(output_dir, exist_ok=True)
print(f"Audio files will be saved in: ./{output_dir}/")

# ==========================================
# 2. LOAD TTS MODEL (VITS Rasa 13)
# ==========================================
print("Loading VITS Rasa 13...")
vits_id = "ai4bharat/vits_rasa_13"
vits_tokenizer = AutoTokenizer.from_pretrained(vits_id, trust_remote_code=True)

vits_config = AutoConfig.from_pretrained(vits_id, trust_remote_code=True)
vits_config.pad_token_id = 0
vits_model = AutoModel.from_pretrained(vits_id, config=vits_config, trust_remote_code=True).to(device)

# ==========================================
# 3. LOAD EVALUATION MODELS
# ==========================================
print("Loading Whisper ASR (Medium)...")
asr_model = whisper.load_model("medium")

print("Loading SpeechBrain S-SIM Model...")
try:
    spk_model = EncoderClassifier.from_hparams(source="speechbrain/spkrec-ecapa-voxceleb", savedir="tmp_dir")
    has_spk_model = True
except Exception as e:
    print(f"Warning: Could not load SpeechBrain. Error: {e}")
    has_spk_model = False

# ==========================================
# 4. HELPER FUNCTIONS
# ==========================================
def calculate_snr(y):
    signal_power = np.mean(y**2)
    noise_floor = np.mean(y[np.abs(y) < np.percentile(np.abs(y), 10)]**2) + 1e-10
    return 10 * np.log10(signal_power / noise_floor)

def clean_hindi_text(text):
    return re.sub(r'[^\u0900-\u097F\s]', '', text).strip()

# ==========================================
# 5. LOAD DATASET & EVALUATE
# ==========================================
print("Loading IndicVoices-R (Hindi Subset)...")
ds = load_dataset("ai4bharat/indicvoices_r", "Hindi", split="train", streaming=True)

results_list = []
print(f"\nStarting Evaluation for {NUM_SAMPLES_TO_TEST} samples...")

for idx, sample in enumerate(ds):
    if idx >= NUM_SAMPLES_TO_TEST:
        break

    print(f"Processing sample {idx + 1}/{NUM_SAMPLES_TO_TEST}...")

    target_text = sample['text']
    ref_audio_array = sample['audio']['array']
    ref_sr = sample['audio']['sampling_rate']

    if ref_sr != 16000:
        ref_audio_array = librosa.resample(y=ref_audio_array, orig_sr=ref_sr, target_sr=16000)

    metrics = {
        "Sample Index": idx,
        "Original Text": target_text
    }

    try:
        # Generate new audio using VITS
        inputs_v = vits_tokenizer(target_text, return_tensors="pt").to(device)
        with torch.no_grad():
            output = vits_model(
                inputs_v['input_ids'],
                speaker_id=1,
                emotion_id=0
            )

        gen_audio = output.waveform.cpu().numpy().squeeze()

        # 🚨 NEW: Save both generated and reference audio permanently
        generated_wav_path = os.path.join(output_dir, f"sample_{idx}_generated.wav")
        reference_wav_path = os.path.join(output_dir, f"sample_{idx}_reference.wav")

        sf.write(generated_wav_path, gen_audio, vits_model.config.sampling_rate)
        sf.write(reference_wav_path, ref_audio_array, 16000) # Librosa resampled it to 16kHz

        # --- Metric 1: Intelligibility (WER) ---
        # Read from the permanently saved file instead of a temp file
        transcription_result = asr_model.transcribe(generated_wav_path, language="hi", task="transcribe", fp16=False)
        transcription = transcription_result["text"]

        clean_target = clean_hindi_text(target_text)
        clean_trans = clean_hindi_text(transcription)

        if len(clean_target) > 0 and len(clean_trans) > 0:
            metrics["WER"] = round(wer(clean_target, clean_trans), 3)
        else:
            metrics["WER"] = 1.0

        metrics["Transcribed Text"] = transcription.strip()

        # --- Metric 2: Clarity (SNR) ---
        metrics["SNR (dB)"] = round(calculate_snr(gen_audio), 2)

        # --- Metric 3: Speaker Similarity ---
        if has_spk_model:
            emb_gen = spk_model.encode_batch(torch.tensor(gen_audio).unsqueeze(0))
            emb_ref = spk_model.encode_batch(torch.tensor(ref_audio_array).unsqueeze(0).float())
            cos = torch.nn.CosineSimilarity(dim=-1)
            metrics["S-SIM"] = round(cos(emb_gen, emb_ref).item(), 3)

    except Exception as e:
        print(f"Error on sample {idx}: {e}")
        metrics["WER"] = "Error"
        metrics["SNR (dB)"] = "Error"
        metrics["S-SIM"] = "Error"
        metrics["Transcribed Text"] = "Error"

    results_list.append(metrics)

# ==========================================
# 6. EXPORT RESULTS
# ==========================================
df_dataset_eval = pd.DataFrame(results_list)
output_csv = "IndicVoices_VITS_Evaluation.csv"
df_dataset_eval.to_csv(output_csv, index=False)

print(f"\n✅ Dataset Evaluation Complete! Results saved to {output_csv}")
print(f"🎧 You can find your 40 audio files (20 generated, 20 reference) in the '{output_dir}' folder in Colab!")
print(f"Average WER: {pd.to_numeric(df_dataset_eval['WER'], errors='coerce').mean():.3f}")
print(f"Average SNR: {pd.to_numeric(df_dataset_eval['SNR (dB)'], errors='coerce').mean():.2f} dB")
print(f"Average S-SIM: {pd.to_numeric(df_dataset_eval['S-SIM'], errors='coerce').mean():.3f}")

import IPython
display(df_dataset_eval.head())

Logging into Hugging Face...
Using device: cuda

Audio files will be saved in: ./IndicVoices_Audio/
Loading VITS Rasa 13...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/1.92k [00:00<?, ?B/s]

configuration_vits.py:   0%|          | 0.00/13.4k [00:00<?, ?B/s]

[transformers] A new version of the following files was downloaded from https://huggingface.co/ai4bharat/vits_rasa_13:
- configuration_vits.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

tokenizer_config.json:   0%|          | 0.00/795 [00:00<?, ?B/s]

tokenization_vits.py:   0%|          | 0.00/7.18k [00:00<?, ?B/s]

[transformers] A new version of the following files was downloaded from https://huggingface.co/ai4bharat/vits_rasa_13:
- tokenization_vits.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

vocab.json:   0%|          | 0.00/17.2k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/275 [00:00<?, ?B/s]

modeling_vits.py:   0%|          | 0.00/68.0k [00:00<?, ?B/s]

[transformers] A new version of the following files was downloaded from https://huggingface.co/ai4bharat/vits_rasa_13:
- modeling_vits.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

model.safetensors:   0%|          | 0.00/161M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/859 [00:00<?, ?it/s]

Loading Whisper ASR (Medium)...

100%|█████████████████████████████████████| 1.42G/1.42G [00:27<00:00, 55.9MiB/s]
INFO:speechbrain.utils.fetching:Fetch hyperparams.yaml: Fetching from HuggingFace Hub 'speechbrain/spkrec-ecapa-voxceleb' if not cached

Loading SpeechBrain S-SIM Model...

hyperparams.yaml:   0%|          | 0.00/1.92k [00:00<?, ?B/s]

INFO:speechbrain.utils.fetching:Fetch embedding_model.ckpt: Fetching from HuggingFace Hub 'speechbrain/spkrec-ecapa-voxceleb' if not cached

embedding_model.ckpt:   0%|          | 0.00/83.3M [00:00<?, ?B/s]

INFO:speechbrain.utils.fetching:Fetch mean_var_norm_emb.ckpt: Fetching from HuggingFace Hub 'speechbrain/spkrec-ecapa-voxceleb' if not cached
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

mean_var_norm_emb.ckpt:   0%|          | 0.00/1.92k [00:00<?, ?B/s]

INFO:speechbrain.utils.fetching:Fetch classifier.ckpt: Fetching from HuggingFace Hub 'speechbrain/spkrec-ecapa-voxceleb' if not cached

classifier.ckpt:   0%|          | 0.00/5.53M [00:00<?, ?B/s]

INFO:speechbrain.utils.fetching:Fetch label_encoder.txt: Fetching from HuggingFace Hub 'speechbrain/spkrec-ecapa-voxceleb' if not cached

label_encoder.txt:   0%|          | 0.00/129k [00:00<?, ?B/s]

INFO:speechbrain.utils.parameter_transfer:Loading pretrained files for: embedding_model, mean_var_norm_emb, classifier, label_encoder
WARNING:speechbrain.inference.interfaces:Could not parse CUDA device string 'cuda': not enough values to unpack (expected 2, got 1). Falling back to device 0.

Loading IndicVoices-R (Hindi Subset)...

README.md:   0%|          | 0.00/33.5k [00:00<?, ?B/s]

Resolving data files:   0%|          | 0/246 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/99 [00:00<?, ?it/s]

Starting Evaluation for 20 samples...
Processing sample 1/20...

[transformers] `use_return_dict` is deprecated! Use `return_dict` instead!

Processing sample 2/20...
Processing sample 3/20...
Processing sample 4/20...
Processing sample 5/20...
Processing sample 6/20...
Processing sample 7/20...
Processing sample 8/20...
Processing sample 9/20...
Processing sample 10/20...
Processing sample 11/20...
Processing sample 12/20...
Processing sample 13/20...
Processing sample 14/20...
Processing sample 15/20...
Processing sample 16/20...
Processing sample 17/20...
Processing sample 18/20...
Processing sample 19/20...
Processing sample 20/20...

✅ Dataset Evaluation Complete! Results saved to IndicVoices_VITS_Evaluation.csv
🎧 You can find your 40 audio files (20 generated, 20 reference) in the 'IndicVoices_Audio' folder in Colab!
Average WER: 0.481
Average SNR: 63.37 dB
Average S-SIM: 0.008

,Sample Index,Original Text,WER,Transcribed Text,SNR (dB),S-SIM
0,0,हमें कृषि के लिए उपयोग में आने वाली विभिन्न वि...,0.400,हमें किसी के लिए उपयोग में आने वाली विभीन विभी...,68.910004,0.023
1,1,हमारे यहाँ जब कटाई होती है तो हम लोग हाइवेस्टर...,0.267,अमारे यहां जब कटाई होती है तो हम लोग हाईवेस्तर...,69.169998,0.008
2,2,ताकि उसमें से जो उसमें से ये है कि हम लोग को उ...,0.333,आक्की उसमे से जो उसमे से यह है कि हम लोग को उस...,61.540001,0.060
3,3,उसमें नी मिलता और जब वहाँ पल हाथ से कटाई करते ...,1.000,,68.239998,-0.008
4,4,अब नहीं होते उससे उसके लिए अलग से ही मसीन आ गई...,0.529,आब नहीं होते उसे उसके लिए अलग से ही मसिन आगई ऐ...,67.580002,-0.023

In [4]:
import shutil
from google.colab import files

# 1. The name of the folder you want to zip
folder_to_download = "IndicVoices_Audio"

# 2. Compress the folder into a .zip file
print(f"Zipping the '{folder_to_download}' folder...")
shutil.make_archive(folder_to_download, 'zip', folder_to_download)

# 3. Trigger the browser download to your local computer
zip_file_name = f"{folder_to_download}.zip"
print(f"Downloading {zip_file_name} to your local machine...")
files.download(zip_file_name)

Zipping the 'IndicVoices_Audio' folder...
Downloading IndicVoices_Audio.zip to your local machine...

In [2]:
!pip install kokoro soundfile openai-whisper librosa jiwer

Collecting kokoro
  Downloading kokoro-0.9.4-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: soundfile in /usr/local/lib/python3.12/dist-packages (0.13.1)
Requirement already satisfied: openai-whisper in /usr/local/lib/python3.12/dist-packages (20250625)
Requirement already satisfied: librosa in /usr/local/lib/python3.12/dist-packages (0.11.0)
Requirement already satisfied: jiwer in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: huggingface-hub in /usr/local/lib/python3.12/dist-packages (from kokoro) (1.17.0)
Requirement already satisfied: loguru in /usr/local/lib/python3.12/dist-packages (from kokoro) (0.7.3)
Collecting misaki>=0.9.4 (from misaki[en]>=0.9.4->kokoro)
  Downloading misaki-0.9.4-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from kokoro) (2.0.2)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from kokoro) (2.11.0+cu128)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (from kokoro) (5.9.0)
Requirement already satisfied: cffi>=1.0 in /usr/local/lib/python3.12/dist-packages (from soundfile) (2.0.0)
Requirement already satisfied: more-itertools in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (10.8.0)
Requirement already satisfied: numba in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (0.60.0)
Requirement already satisfied: tiktoken in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (0.13.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (4.67.3)
Requirement already satisfied: triton>=2 in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (3.6.0)
Requirement already satisfied: audioread>=2.1.9 in /usr/local/lib/python3.12/dist-packages (from librosa) (3.1.0)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from librosa) (1.16.3)
Requirement already satisfied: scikit-learn>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from librosa) (1.6.1)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.12/dist-packages (from librosa) (1.5.3)
Requirement already satisfied: decorator>=4.3.0 in /usr/local/lib/python3.12/dist-packages (from librosa) (4.4.2)
Requirement already satisfied: pooch>=1.1 in /usr/local/lib/python3.12/dist-packages (from librosa) (1.9.0)
Requirement already satisfied: soxr>=0.3.2 in /usr/local/lib/python3.12/dist-packages (from librosa) (1.1.0)
Requirement already satisfied: typing_extensions>=4.1.1 in /usr/local/lib/python3.12/dist-packages (from librosa) (4.15.0)
Requirement already satisfied: lazy_loader>=0.1 in /usr/local/lib/python3.12/dist-packages (from librosa) (0.5)
Requirement already satisfied: msgpack>=1.0 in /usr/local/lib/python3.12/dist-packages (from librosa) (1.1.2)
Requirement already satisfied: click>=8.1.8 in /usr/local/lib/python3.12/dist-packages (from jiwer) (8.4.1)
Requirement already satisfied: rapidfuzz>=3.9.7 in /usr/local/lib/python3.12/dist-packages (from jiwer) (3.14.5)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.0->soundfile) (3.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from lazy_loader>=0.1->librosa) (26.2)
Collecting addict (from misaki>=0.9.4->misaki[en]>=0.9.4->kokoro)
  Downloading addict-2.4.0-py3-none-any.whl.metadata (1.0 kB)
Requirement already satisfied: regex in /usr/local/lib/python3.12/dist-packages (from misaki>=0.9.4->misaki[en]>=0.9.4->kokoro) (2025.11.3)
Collecting espeakng-loader (from misaki[en]>=0.9.4->kokoro)
  Downloading espeakng_loader-0.2.4-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.3 kB)
Collecting num2words (from misaki[en]>=0.9.4->kokoro)
  Downloading num2words-0.5.14-py3-none-any.whl.metadata (13 kB)
Collecting phonemizer-fork (from misaki[en]>=0.9.4->kokoro)
  Downloading phonemizer_fork-3.3.2-py3-none-any.whl.metadata (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.3/48.3 kB 3.0 MB/s eta 0:00:00
Requirement already satisfied: spacy in /usr/local/lib/python3.12/dist-packages (from misaki[en]>=0.9.4->kokoro) (3.8.14)
Collecting spacy-curated-transformers (from misaki[en]>=0.9.4->kokoro)
  Downloading spacy_curated_transformers-2.1.2-py2.py3-none-any.whl.metadata (2.8 kB)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba->openai-whisper) (0.43.0)
Requirement already satisfied: platformdirs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from pooch>=1.1->librosa) (4.10.0)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from pooch>=1.1->librosa) (2.32.4)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.1.0->librosa) (3.6.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub->kokoro) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub->kokoro) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub->kokoro) (1.5.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub->kokoro) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub->kokoro) (6.0.3)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub->kokoro) (0.25.1)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch->kokoro) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch->kokoro) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch->kokoro) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->kokoro) (3.1.6)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->kokoro) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch->kokoro) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch->kokoro) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch->kokoro) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch->kokoro) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch->kokoro) (3.4.5)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->kokoro) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->kokoro) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->kokoro) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->kokoro) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->kokoro) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->kokoro) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->kokoro) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->kokoro) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->kokoro) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->kokoro) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->kokoro) (12.8.90)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers->kokoro) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers->kokoro) (0.7.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch->kokoro) (1.5.5)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub->kokoro) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub->kokoro) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub->kokoro) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub->kokoro) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub->kokoro) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->pooch>=1.1->librosa) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->pooch>=1.1->librosa) (2.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch->kokoro) (1.3.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub->kokoro) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub->kokoro) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub->kokoro) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch->kokoro) (3.0.3)
Collecting docopt>=0.6.2 (from num2words->misaki[en]>=0.9.4->kokoro)
  Downloading docopt-0.6.2.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: attrs>=18.1 in /usr/local/lib/python3.12/dist-packages (from phonemizer-fork->misaki[en]>=0.9.4->kokoro) (26.1.0)
Collecting dlinfo (from phonemizer-fork->misaki[en]>=0.9.4->kokoro)
  Downloading dlinfo-2.0.0-py3-none-any.whl.metadata (1.1 kB)
Collecting segments (from phonemizer-fork->misaki[en]>=0.9.4->kokoro)
  Downloading segments-2.4.0-py2.py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy->misaki[en]>=0.9.4->kokoro) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy->misaki[en]>=0.9.4->kokoro) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy->misaki[en]>=0.9.4->kokoro) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy->misaki[en]>=0.9.4->kokoro) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy->misaki[en]>=0.9.4->kokoro) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in /usr/local/lib/python3.12/dist-packages (from spacy->misaki[en]>=0.9.4->kokoro) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy->misaki[en]>=0.9.4->kokoro) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from spacy->misaki[en]>=0.9.4->kokoro) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy->misaki[en]>=0.9.4->kokoro) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy->misaki[en]>=0.9.4->kokoro) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from spacy->misaki[en]>=0.9.4->kokoro) (1.3.3)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy->misaki[en]>=0.9.4->kokoro) (2.12.3)
Collecting curated-transformers<3.0.0,>=2.0.0 (from spacy-curated-transformers->misaki[en]>=0.9.4->kokoro)
  Downloading curated_transformers-2.0.1-py2.py3-none-any.whl.metadata (5.3 kB)
Collecting curated-tokenizers<3.0.0,>=2.0.0 (from spacy-curated-transformers->misaki[en]>=0.9.4->kokoro)
  Downloading curated_tokenizers-2.0.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.9 kB)
INFO: pip is looking at multiple versions of spacy-curated-transformers to determine which version is compatible with other requirements. This could take a while.
Collecting spacy-curated-transformers (from misaki[en]>=0.9.4->kokoro)
  Downloading spacy_curated_transformers-2.1.1-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting spacy (from misaki[en]>=0.9.4->kokoro)
  Downloading spacy-4.0.0.dev3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (26 kB)
Collecting spacy-curated-transformers (from misaki[en]>=0.9.4->kokoro)
  Downloading spacy_curated_transformers-2.0.0-py2.py3-none-any.whl.metadata (2.8 kB)
  Downloading spacy_curated_transformers-0.3.1-py2.py3-none-any.whl.metadata (2.7 kB)
Collecting curated-transformers<0.2.0,>=0.1.0 (from spacy-curated-transformers->misaki[en]>=0.9.4->kokoro)
  Downloading curated_transformers-0.1.1-py2.py3-none-any.whl.metadata (965 bytes)
Collecting curated-tokenizers<0.1.0,>=0.0.9 (from spacy-curated-transformers->misaki[en]>=0.9.4->kokoro)
  Downloading curated_tokenizers-0.0.9-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.9 kB)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy->misaki[en]>=0.9.4->kokoro) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy->misaki[en]>=0.9.4->kokoro) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy->misaki[en]>=0.9.4->kokoro) (0.4.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub->kokoro) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub->kokoro) (2.20.0)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.12->spacy->misaki[en]>=0.9.4->kokoro) (1.3.3)
Requirement already satisfied: cloudpathlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy->misaki[en]>=0.9.4->kokoro) (0.24.0)
Requirement already satisfied: smart-open>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy->misaki[en]>=0.9.4->kokoro) (7.6.1)
Collecting csvw>=1.5.6 (from segments->phonemizer-fork->misaki[en]>=0.9.4->kokoro)
  Downloading csvw-4.0.0-py2.py3-none-any.whl.metadata (10 kB)
Collecting isodate (from csvw>=1.5.6->segments->phonemizer-fork->misaki[en]>=0.9.4->kokoro)
  Downloading isodate-0.7.2-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from csvw>=1.5.6->segments->phonemizer-fork->misaki[en]>=0.9.4->kokoro) (2.9.0.post0)
Collecting rfc3986<2 (from csvw>=1.5.6->segments->phonemizer-fork->misaki[en]>=0.9.4->kokoro)
  Downloading rfc3986-1.5.0-py2.py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: uritemplate>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from csvw>=1.5.6->segments->phonemizer-fork->misaki[en]>=0.9.4->kokoro) (4.2.0)
Requirement already satisfied: babel in /usr/local/lib/python3.12/dist-packages (from csvw>=1.5.6->segments->phonemizer-fork->misaki[en]>=0.9.4->kokoro) (2.18.0)
Collecting language-tags (from csvw>=1.5.6->segments->phonemizer-fork->misaki[en]>=0.9.4->kokoro)
  Downloading language_tags-1.3.1-py3-none-any.whl.metadata (6.5 kB)
Collecting rdflib (from csvw>=1.5.6->segments->phonemizer-fork->misaki[en]>=0.9.4->kokoro)
  Downloading rdflib-7.6.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: termcolor in /usr/local/lib/python3.12/dist-packages (from csvw>=1.5.6->segments->phonemizer-fork->misaki[en]>=0.9.4->kokoro) (3.3.0)
Requirement already satisfied: jsonschema in /usr/local/lib/python3.12/dist-packages (from csvw>=1.5.6->segments->phonemizer-fork->misaki[en]>=0.9.4->kokoro) (4.26.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub->kokoro) (0.1.2)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy->misaki[en]>=0.9.4->kokoro) (2.2.1)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema->csvw>=1.5.6->segments->phonemizer-fork->misaki[en]>=0.9.4->kokoro) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema->csvw>=1.5.6->segments->phonemizer-fork->misaki[en]>=0.9.4->kokoro) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema->csvw>=1.5.6->segments->phonemizer-fork->misaki[en]>=0.9.4->kokoro) (2026.5.1)

In [4]:
import os
import numpy as np
import soundfile as sf
from kokoro import KPipeline

print("Initializing Kokoro (82M) Pipeline for Hindi...")
# 'h' is the language code for Hindi
pipeline = KPipeline(lang_code='h')

prompt_text = "नमस्ते, मेरा नाम जय है।"

# Dictionary mapping file names to the Kokoro voice ID
voices_to_test = {
    "kokoro_male.wav": "hm_omega",
    "kokoro_female.wav": "hf_alpha"  # You can also try "hf_beta"
}

for filename, voice_id in voices_to_test.items():
    print(f"\nGenerating {filename} using voice: {voice_id}...")

    try:
        # Generate the audio chunks
        generator = pipeline(prompt_text, voice=voice_id, speed=1.0)
        audio_pieces = [audio for _, _, audio in generator]

        if audio_pieces:
            # Combine chunks and save at 24kHz
            final_audio = np.concatenate(audio_pieces)
            sf.write(filename, final_audio, 24000)
            print(f"✅ Saved successfully as {filename}")
        else:
            print(f"❌ Failed to generate audio for {voice_id}.")

    except Exception as e:
        print(f"❌ Error generating {voice_id}: {e}")

print("\n🎉 Generation complete! Both files are ready to download.")

Initializing Kokoro (82M) Pipeline for Hindi...
WARNING: Defaulting repo_id to hexgrad/Kokoro-82M. Pass repo_id='hexgrad/Kokoro-82M' to suppress this warning.

/usr/local/lib/python3.12/dist-packages/torch/nn/modules/rnn.py:1013: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.2 and num_layers=1
  super().__init__("LSTM", *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/torch/nn/utils/weight_norm.py:144: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)

Generating kokoro_male.wav using voice: hm_omega...
✅ Saved successfully as kokoro_male.wav

Generating kokoro_female.wav using voice: hf_alpha...

voices/hf_alpha.pt:   0%|          | 0.00/523k [00:00<?, ?B/s]

✅ Saved successfully as kokoro_female.wav

🎉 Generation complete! Both files are ready to download.

In [5]:
import os
import re
import numpy as np
import pandas as pd
import librosa
import torch
import whisper
from jiwer import wer
from speechbrain.inference.speaker import EncoderClassifier

# ==========================================
# 1. CONFIGURATION
# ==========================================
PROMPT_TEXT = "नमस्ते, मेरा नाम जय है।"
REFERENCE_AUDIO = "jay_reference.wav"
files_to_evaluate = ["kokoro_male.wav", "kokoro_female.wav"]

# ==========================================
# 2. LOAD EVALUATION MODELS
# ==========================================
print("Loading Whisper ASR (Medium)...")
asr_model = whisper.load_model("medium")

print("Loading SpeechBrain S-SIM Model...")
try:
    spk_model = EncoderClassifier.from_hparams(source="speechbrain/spkrec-ecapa-voxceleb", savedir="tmp_dir")
    has_spk_model = True
except Exception as e:
    print(f"Warning: Could not load SpeechBrain. Error: {e}")
    has_spk_model = False

# ==========================================
# 3. HELPER FUNCTIONS
# ==========================================
def calculate_snr(y):
    signal_power = np.mean(y**2)
    noise_floor = np.mean(y[np.abs(y) < np.percentile(np.abs(y), 10)]**2) + 1e-10
    return 10 * np.log10(signal_power / noise_floor)

def clean_hindi_text(text):
    return re.sub(r'[^\u0900-\u097F\s]', '', text).strip()

# ==========================================
# 4. EVALUATION LOOP
# ==========================================
results_list = []
print("\nStarting Kokoro Evaluation...")

for audio_path in files_to_evaluate:
    if not os.path.exists(audio_path):
        print(f"⚠️ File not found: {audio_path}. Did you generate it in the previous step?")
        continue

    print(f"Evaluating: {audio_path} ...")
    metrics = {"File Name": audio_path, "Model": "Kokoro (82M)"}

    try:
        # Load audio (Librosa auto-resamples 24kHz Kokoro output to 16kHz for evaluation)
        y, sr = librosa.load(audio_path, sr=16000)

        # --- Metric 1: Intelligibility (WER) ---
        transcription_result = asr_model.transcribe(
            audio_path,
            language="hi",
            task="transcribe",
            fp16=False
        )
        transcription = transcription_result["text"]

        clean_target = clean_hindi_text(PROMPT_TEXT)
        clean_trans = clean_hindi_text(transcription)

        if len(clean_target) > 0 and len(clean_trans) > 0:
            metrics["WER"] = round(wer(clean_target, clean_trans), 3)
        else:
            metrics["WER"] = 1.0

        metrics["Transcribed Text"] = transcription.strip()

        # --- Metric 2: Clarity (SNR) ---
        metrics["SNR (dB)"] = round(calculate_snr(y), 2)

        # --- Metric 3: Speaker Similarity ---
        if has_spk_model and os.path.exists(REFERENCE_AUDIO):
            sig_ref, _ = librosa.load(REFERENCE_AUDIO, sr=16000)

            emb_gen = spk_model.encode_batch(torch.tensor(y).unsqueeze(0))
            emb_ref = spk_model.encode_batch(torch.tensor(sig_ref).unsqueeze(0))

            cos = torch.nn.CosineSimilarity(dim=-1)
            metrics["S-SIM"] = round(cos(emb_gen, emb_ref).item(), 3)
        else:
            metrics["S-SIM"] = "N/A"

    except Exception as e:
        print(f"Error evaluating {audio_path}: {e}")
        metrics.update({"WER": "Error", "Transcribed Text": "Error", "SNR (dB)": "Error", "S-SIM": "Error"})

    results_list.append(metrics)

# ==========================================
# 5. DISPLAY RESULTS
# ==========================================
if results_list:
    df_results = pd.DataFrame(results_list)

    # Save specifically for Kokoro
    output_csv = "Kokoro_Evaluation_Results.csv"
    df_results.to_csv(output_csv, index=False)

    print("\n" + "="*50)
    print("🧡 KOKORO EVALUATION COMPLETE")
    print("="*50)
    import IPython
    display(df_results)

Loading Whisper ASR (Medium)...

INFO:speechbrain.utils.fetching:Fetch hyperparams.yaml: Using symlink found at '/content/tmp_dir/hyperparams.yaml'

Loading SpeechBrain S-SIM Model...

INFO:speechbrain.utils.fetching:Fetch embedding_model.ckpt: Using symlink found at '/content/tmp_dir/embedding_model.ckpt'
INFO:speechbrain.utils.fetching:Fetch mean_var_norm_emb.ckpt: Using symlink found at '/content/tmp_dir/mean_var_norm_emb.ckpt'
INFO:speechbrain.utils.fetching:Fetch classifier.ckpt: Using symlink found at '/content/tmp_dir/classifier.ckpt'
INFO:speechbrain.utils.fetching:Fetch label_encoder.txt: Using symlink found at '/content/tmp_dir/label_encoder.ckpt'
INFO:speechbrain.utils.parameter_transfer:Loading pretrained files for: embedding_model, mean_var_norm_emb, classifier, label_encoder
WARNING:speechbrain.inference.interfaces:Could not parse CUDA device string 'cuda': not enough values to unpack (expected 2, got 1). Falling back to device 0.

Starting Kokoro Evaluation...
Evaluating: kokoro_male.wav ...
Evaluating: kokoro_female.wav ...

==================================================
🧡 KOKORO EVALUATION COMPLETE
==================================================

,File Name,Model,WER,Transcribed Text,SNR (dB),S-SIM
0,kokoro_male.wav,Kokoro (82M),0.4,नमस्ते मेरा नाम जैहें,78.489998,N/A
1,kokoro_female.wav,Kokoro (82M),0.4,नमस्ते मेरा नाम जैहे,79.110001,N/A